### ISSUE TITLE
Add `diredfl-no-priv` when missing a directory/link priv indicator

### ISSUE THREAD

**Issue by slotThe** [purcell/diredfl#15]
Hi,

right now `diredfl-no-priv` is only applied when an ordinary privilege (rwx) is missing; for "special" indicators, like directories and links, no face is used.  When font-locking the file modes column with a background colour, this can look rather awkward: 

![2022-05-06-191209_728x209_scrot](https://user-images.githubusercontent.com/50166980/167242140-e48b99ca-9edb-4842-a514-4e299fa68aae.png)

Would it be possible to give that first `-` the `diredfl-no-priv` face as well?

**Comment by purcell** [comment]
Are you sure the face being applied to the leading `d`/`l` is `diredfl-no-priv`?

**Comment by slotThe** [comment]
Sorry, I wasn't very clear.  The face applied to `d` and `l` is indeed `dired-dir-priv` and `dired-rare-priv`, respectively.  However, there is no face applied to `-` _in place of_ `d` or `l` (i.e., if these privileges are missing).  For the other privileges (`-` in the spots of `r`, `w`, and `x`), the `diredfl-no-priv` is used instead of `diredfl-{read,write,exec}-priv`; I'd like that to happen for a "missing" `d` or `l` as well

**Comment by purcell** [comment]
Done, I think!

**Comment by slotThe** [comment]
Indeed, thank you!
