### ISSUE TITLE
Font-locking looks odd when username has number in it

### ISSUE THREAD

**Issue by raxod502** [purcell/diredfl#2]
Behold!

![image](https://user-images.githubusercontent.com/6559064/31573186-58897738-b06b-11e7-8a04-ca1e54ca3694.png)

As its name suggests, the face `diredfl-number` is applied to all numbers in the Dired buffer. This looks quite odd when a username has a number in it, as shown above.

**Comment by raxod502** [comment]
![image](https://user-images.githubusercontent.com/6559064/31580696-6d5fb482-b10c-11e7-89e4-245a75684d50.png)

Unfortunately, it still looks odd when using revision 45e9c46f58c655694758d4986b9195c8bb40ddf3.

**Comment by purcell** [comment]
Hrm. Are you absolutely sure you've got the new version loaded, and no trace of the old font lock definitions? ie. you've restarted Emacs after installing the new package? I tested this locally against sample text, but stopped short of creating a user whose name contains a number, and before I go to all that trouble I'd like to be certain it's necessary! :-)

**Comment by raxod502** [comment]
Sorry. My best guess as to what happened is that there was a bug in my package manager that caused the new version to not be recompiled, so the old definitions were still loaded.

In any case, the problem is fixed! Thanks.

![image](https://user-images.githubusercontent.com/6559064/31587272-99a3f35a-b193-11e7-8000-b8eecbf0b97d.png)

**Comment by purcell** [comment]
Yay, thanks for confirming! :-)
