### ISSUE TITLE
See also dired-rainbow

### ISSUE THREAD

**Issue by Fuco1** [purcell/diredfl#3]
I've written a somewhat similar package https://github.com/Fuco1/dired-hacks#dired-rainbow maybe we could somehow combine things together?

Though you seem to provide a bit orthogonal functionality, I'm more about fontifying file names based on rules, but I can see some overlap.

**Comment by purcell** [comment]
All I did here was extract the extra fontification stuff from `dired+`, which is unlikely to ever move off the Emacswiki, and will therefore be removed from MELPA soon -- this was the only part of that package I used. As such, I'm not really planning to maintain it actively, but I'm open to merging if you think it would be a good idea. :-)

**Comment by Fuco1** [comment]
That makes sense.

Maybe I'll just add a backlink to point people here as well, feel free to do the same :)  It seems the project have a bit different scope after all.

**Comment by Fuco1** [comment]
https://github.com/Fuco1/dired-hacks/commit/f4f2f3ade3b592502b8336bc9d10288ae00679ad

Sending :heart:  your way as well!
