### ISSUE TITLE
diredfl-ignore-compressed-flag set to nil not working?

### ISSUE THREAD

**Issue by dieggsy** [purcell/diredfl#4]
I have `dired-fl-ignore-compressed-flag` set to `nil` but compressed files are still being font-locked as ignored.

**Comment by purcell** [comment]
It looks like you'd need to set that variable before loading `diredfl`. Is that perhaps the problem? The original author didn't really set things up to reliably honour the flag, and I might even remove it.

**Comment by dieggsy** [comment]
Thanks, that worked. I'd say while I don't feel extremely strongly about it, I generally think it might be good to have a way to customize what types of files are ignored. Seems the package uses `dired-omit-extensions` and `completion-ignored-extensions`, but one might want to omit files that are that are in neither list (`e.g.` someone wants to "ignore" but not omit auto save files or something.)
