### ISSUE TITLE
dired-mark highlights

### ISSUE THREAD

**Issue by manuel-uberti** [purcell/diredfl#7]
Following [#6](https://github.com/purcell/diredfl/pull/6), files/directories marked for deletion are properly highlighted now.

However, files/directories marked with `dired-mark` look like this:
![1](https://user-images.githubusercontent.com/8199224/36071092-34001442-0f09-11e8-9af6-70407f1b931e.png)

This is how they look without `diredfl-mode` active:
![2](https://user-images.githubusercontent.com/8199224/36071095-3e3aa35a-0f09-11e8-9e18-db900b67d282.png)

The highlight on the file/directory names makes it clearer, IMHO.

**Comment by manuel-uberti** [comment]
Forgot to mention @ubolonton on this. :)

**Comment by ubolonton** [comment]
It seems you are using another package that highlights alternate lines in dired. In that case you can:
- Customize `diredfl-flag-mark-line` and `diredfl-deletion-file-name` faces to add desired `:foreground` colors.
- Request the theme to support both `diredfl` and that package together.

**Comment by manuel-uberti** [comment]
You're right. I'll ping the author then. Thanks.

**Comment by manuel-uberti** [comment]
I can confirm everything looks good with `stripe-buffer` disabled. Thank you again, @ubolonton.
